FROM mysql:8.0.20

# ENV MYSQL_ROOT_PASSWORD DEFAULT_PASS
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true
ENV MYSQL_DATABASE=customer
ENV MYSQL_USER=unisannio
ENV MYSQL_PASSWORD=unisannio

RUN usermod -u 1000 mysql

EXPOSE 3306