FROM mysql:8.0.20

ENV MYSQL_ROOT_PASSWORD=unisannio
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true
ENV MYSQL_DATABASE=customer
ENV MYSQL_USER=unisannio
ENV MYSQL_PASSWORD=unisannio

RUN rm -fr /var/lib/mysql

EXPOSE 3306